[images]
  remote_images = ["*.placeholder.com", "*.unsplash.com"]

[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
